/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple.games;

import simple.games.services.GameManager;

public class App {
    public static void main(String[] args) {

        try{
            GameManager gameManager = new GameManager();

            gameManager.startGame();
        }catch(Throwable e){
            e.printStackTrace();
        }
    }
}
