/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple.games;

import simple.games.services.Game;
import simple.games.services.GameManager;

public class App {
    public static void main(String[] args) {

        GameManager gameManager = new GameManager();

        Game currentGame = gameManager.chooseGame();

        currentGame.initialize();
        currentGame.play();
        currentGame.end();
    }
}
